<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "sf_seolighthouse"
 *
 * Auto generated by Extension Builder 2021-03-21
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'SEO Lighthouse Score',
    'description' => 'Shows Lighthouse Score in Frontend, Backend and TYPO3 Console',
    'category' => 'misc',
    'author' => 'Andreas Kauhold',
    'author_email' => 'info@stackfactory.de',
    'state' => 'alpha',
    'clearCacheOnLoad' => 0,
    'version' => '1.0.0',
    'constraints' => [
        'depends' => [
            'typo3' => '10.4.0-10.4.99',
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];
